name: Tests
on: 
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # the tests need to confirm that querying the databases works (as that's the
        # purpose of the package), but to limit the number of queries, just test on 
        # a single version
        python-version: ['3.13']

    steps:
    - name: Check out code 
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install package and dependencies
      run: |
        pip install setuptools --upgrade
        pip install git+https://github.com/mfouesneau/ezpadova.git
        pip install .[dev]

    - name: Run unit tests
      run: |
        mkdir -p test-reports
        py.test -v --junitxml=test-reports/junit.xml test/*.py
